name: Hprofile Test Workflow

on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Testing Workflow
        uses: actions/checkout@v5

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn Checkstyle:checkstyle 
