name: CI Test Workflow

on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Testing Workflow
        run: echo "Workflow Works!"
